# Generated by Django 2.1 on 2024-03-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20240319_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='numbers_in_stock',
            new_name='number_in_stock',
        ),
    ]
